sudo: false
cache: bundler
language: ruby
rvm:
  - '2.0'
  - '2.1'
  - '2.2'

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - Gemfile

script: "bundle exec rspec"
